AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
    Function:
        Layers:
            - !Ref RuntimeDependenciesLayer
Resources:
    Notif19:
        Type: 'AWS::Serverless::Function'
        Metadata:
            BuildMethod: makefile
        Properties:
            Handler: dist/index.handler
            Runtime: nodejs12.x
            Timeout: 900
            Description: Retrieves daily COVID-19 case data by Canadian province and sends it via text message to subscribers.
            Environment:
                Variables:
                    TWILIO_ACCOUNT_SID: 'AC75558b0252f11b43713b7a4aa6ea8f84'
                    TWILIO_AUTH_TOKEN: '5a86465fed6f28fafff6f269a6a3326a'
                    MONGO_USER: 'admin-jyt'
                    MONGO_PASS: 'p2W2^nPGbuz9'
                    MOMGO_DB_NAME: 'percy'
                    TWILIO_PHONE_NUMBER: '+14159660125'
            Events:
                StartScheduledEvent:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 16 ? * 1-5 *)

    RuntimeDependenciesLayer:
        Type: AWS::Serverless::LayerVersion
        Metadata:
            BuildMethod: makefile
        Properties:
            Description: Runtime dependencies
            ContentUri: ./
            CompatibleRuntimes:
                - nodejs12.x
            RetentionPolicy: Retain
